<html>

<head></head>

<body>

<div>

<h1 style="width:200px;height:50xp;background:orange;display:block;margin:0px;border:5px solid green;padding:10px;text-align:center">我的个人简介</h1>

</div>

<div style="background:orange;text-align:center;padding:40px">

<img src="https://imgloc.com/i/HCdoq" alt="QQ头像" width="40px";height="30px">

</div>

<div style="max-width:1000px">大家好，我是练习时长两年半的笑红鏖[QQ网名]，你我来到这里，其实都是缘分我嘛，我这个人嘛虽然说算不上非常好，但也是差不多了如果现在你还能看到这一段话的话，那么说明肯定是几年后的事情了其实这个东西一开始就是我小学的时候啊，简单写了一个文件然后现在我又开始来修饰它这是我修饰的第一天所以我就只添加了一个个人简介啊，后续呢，我还会继续进行更新啊，关注github的个人账号仁文莫克就可以了</div>

<div style="background-clour:white;text-align:center;padding:40px;font- size:12px">

<p>推荐几个好网站</p>

<a href="http://www.wesane.com/game/654/">合成西瓜籽http://www.wesane.com/game/654/

<a href="https://yunyi.rth1.one">某个个人网站</a

<a href="g.wazf.top/299">后面那个299数字可以随便改</a>

</a>

</div>

</body>    

 </html>

 
